ebuy/ebuy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reg_login.urls', namespace='reg_login')),
    path('test/', include('per_info.urls', namespace='per_info')),
]

ebuy/per_info/urls.py
from django.urls import path, re_path
from . import views

app_name = 'per_info'
urlpatterns = [
    path('info_main/', views.info_main, name='info_main'),
    path('info_main/show_info', views.show_info, name='show_info'),
    path('info_main/modify_info', views.modify_info, name='modify_info'),
    path('info_main/modify_pwd', views.modify_pwd, name='modify_pwd'),
    path('info_main/handle_page_one', views.handle_page_one, name='handle_page_one'),
    re_path('info_main/handle_page_two/(?P<phone_number>[0-9]+)$', views.handle_page_two, name='handle_page_two'),
    re_path('info_main/handle_page_three/(?P<phone_number>[0-9]+)$', views.handle_page_three, name='handle_page_three'),
    path('index/', views.test)
]

ebuy/reg_login/urls.py
from django.urls import path, re_path
from . import views

app_name = 'reg_login'
urlpatterns = [
    path('', views.dispatcher),
    path('index/', views.index, name='index'),
    path('reg_login/login', views.login, name='login'),
    path('reg_login/reg', views.reg, name='reg'),
    path('reg_login/handle_reg', views.handle_reg, name='handle_reg'),
    path('reg_login/handle_login', views.handle_login, name='handle_login'),
    path('reg_login/logout', views.logout, name='logout')
]

ebuy/per_info/models.py
from django.db import models
# Create your models here.

ebuy/per_info/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models
from django.template import loader ,Context
from django.http import HttpResponse
import os, time
from reg_login import models

# Create your views here.


def test(request):
    user_one = models.User.objects.filter(pk='18829035792')
    user_one = user_one[0]
    p = user_one.user_verify.all()
    if not p:
        p = 'nothing'

    return render(request, 'templates/per_info/index.html', {'user_one': user_one, 'p': p})


def info_main(request):
    return render(request, 'templates/per_info/info_main.html')


def show_info(request):
    is_login = request.session.get('is_login', None)
    if not is_login:
        return redirect('reg_login:login')
    user_phone = request.session.get("user_phone", None)
    user = models.User.objects.filter(pk=user_phone)
    user = user[0]
    return render(request, 'templates/per_info/show_info.html', {'user': user})


def modify_info(request):
    if request.method == 'GET':
        return redirect('reg_login:index')
    if request.method == 'POST':
        flag = 0
        user_phone = request.session.get("user_phone", None)
        if user_phone:
            user = models.User.objects.filter(pk=user_phone)
            user = user[0]
            user.user_nickname = request.POST.get('user_nickname')
            try:
                image = request.FILES.get('upload', None)
                if image:
                    user.user_pic = str(int(time.time()*10000)) + '.jpg'
                    dist = open(os.path.join('./reg_login/static/profile/', user.user_pic), 'wb')
                    for chunk in image.chunks():
                        dist.write(chunk)
                    dist.close()
            except:
                flag = 1

            if flag != 0:
                return HttpResponse('error')
            else:
                user.save()
                return redirect('per_info:show_info')
        else:
            return redirect('reg_login:index')


def modify_pwd(request):
    return render(request, 'templates/per_info/secure_change_pwd1.html')


def handle_page_one(request):
    if request.method == 'GET':
        return redirect('per_info:modify_pwd')
    flag = 0
    if request.method == 'POST':
        user_phone = request.POST.get('phone')
        user = models.User.objects.filter(pk=user_phone)
        if not user:
            flag += 2
            return render(request, 'templates/per_info/secure_change_pwd1.html', {'flag': flag})
        else:
            user = user[0]
            questions = user.user_verify.all()
            questions_show = []
            for question in questions:
                questions_show.append(question.user_verify_question)
            return render(request, 'templates/per_info/secure_change_pwd2.html', {'phone': user.user_phone, 'questions': questions_show})
    else:
        flag += 1
        return render(request, 'templates/per_info/secure_change_pwd1.html', {'flag': flag})


def handle_page_two(request, phone_number):
    if request.method == 'GET':
        return redirect('per_info:modify_pwd')
    if request.method == 'POST':
        user = models.User.objects.filter(pk=phone_number)

        if not user:
            return render(request, 'templates/per_info/secure_change_pwd2.html', {'flag': 2, 'phone': phone_number})
        else:
            user = user[0]
            answer = user.user_verify.all()
            if answer[0].user_verify_question == '父亲姓名':
                answer_one = answer[0].user_verify_answer
                answer_two = answer[1].user_verify_answer
            else:
                answer_one = answer[1].user_verify_answer
                answer_two = answer[0].user_verify_answer
            need_to_verify_one = request.POST.get('father_name')
            need_to_verify_two = request.POST.get('mother_name')
            if answer_one and answer_two:
                if answer_one == need_to_verify_one and answer_two == need_to_verify_two:
                    return render(request, 'templates/per_info/secure_change_pwd3.html', {'phone': phone_number})
                else:
                    return render(request, 'templates/per_info/secure_change_pwd2.html', {'flag': 3, 'phone': phone_number})

            return render(request, 'templates/per_info/secure_change_pwd2.html', {'flag': 3, 'phone': phone_number})
    else:
        return render(request, 'templates/per_info/secure_change_pwd2.html', {'flag': 0, 'phone': phone_number})


def handle_page_three(request, phone_number):
    if request.method == 'GET':
        return redirect('per_info:modify_pwd')
    if request.method == 'POST':
        user = models.User.objects.filter(pk=phone_number)

        if not user:
            return render(request, 'templates/per_info/secure_change_pwd3.html', {'flag': 5, 'phone': phone_number})
        else:
            user = user[0]
            pwd1 = request.POST.get('password1')
            pwd2 = request.POST.get('password2')
            if pwd1 and pwd2:
                if pwd1 == pwd2:
                    user.user_password = pwd1
                    user.save()
                    return render(request, 'templates/per_info/secure_change_pwd4.html')
                else:
                    return render(request, 'templates/per_info/secure_change_pwd3.html', {'flag': 4, 'phone': phone_number})

            return render(request, 'templates/per_info/secure_change_pwd3.html', {'flag': 6, 'phone': phone_number})
    else:
        return render(request, 'templates/per_info/secure_change_pwd3.html', {'flag': 7, 'phone': phone_number})

ebuy/per_info/templates/per_info/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{user_one.user_phone}}
    <br>
    {{p}}
</body>
</html>

ebuy/per_info/templates/per_info/info_main.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>个人信息主页</title>
		<style type="text/css">
			body{
				width:100%;
				height:100%;
			}
			* {
				padding: 0;
				margin: 0;
			}
			.header {
				text-align: center;
				padding-top: 12px;
				padding-bottom: 12px;
				background: #ff4401;
			}
			a ,a:visited, a:link{
				text-decoration: none;
				cursor: pointer;
				color:white;
			}
			.nav {
				width: 1000px;
				margin: 0 auto;
				font-size: 0;
				color:white;
			}
			.nav>ul>li{
				display:inline-block;
				position: relative;
				bottom: 8px;
			}
			.nav>ul>li>a {
				font-size: 18px;
				display: inline-block;
				width: 100px;
			}
			.nav>ul>li>a:hover {
				background-color: #942b06;
			}
			.local {
				margin-left: 30px;
			}
			.adm {
				margin-left: 25px;
			}
			.content img{
				width:1519px;
				height:1849px;
			}
			.clearfix{
                *zoom:1;
            }
            .clearfix:after{
                clear: both;
            }
			.two,.two>li{list-style: none;}
			.two{display:none;font-size: 12px;}
			.ul_one>li:hover .two{display: block;}{
				
			}
			.two li{height:20px;width:200%;padding: 10px 0;transition: .4s;color:black;background-color:white;    border-left: solid;
				border-right: solid;
				border-color: #90dae633;
			}
			.two li:hover{}
			.two li a:hover{
				color:#ff4401;
				
			}
			.two a{
				color:black;
			}
			#main_page_one{
				width:auto;
			}
			#main_page_one:hover{
				background:none;
			}
		</style>
	</head>
 
	<body>
		<div class="header">
			<div class="nav clearfix">
				<ul class="ul_one">
					<li style="margin-right:20px;position: initial;"><a href="{% url 'reg_login:index' %}" id="main_page_one"><img src="/static/img/logo_new.jpg" style="width: 130px;height: 35px;"></a></li>
					<li><a href="{% url 'per_info:info_main' %}" style="margin-right:20px;">首页</a></li>
					<li>
						<a style="margin-right:15px;">账户设置 ˇ</a>
						<ul class="two" style="z-index: 99999;width:85px; position: absolute;left: -38px;top: 15px;">
							<li style="margin-top:9px; border-top:solid;border-top-color:#90dae633;"><a href="{% url 'per_info:show_info' %}">个人资料</a></li>
							<li style="border-bottom:solid;border-bottom-color:#90dae633;"><a href="{% url 'per_info:modify_pwd' %}" target="_blank">修改密码</a></li>
						</ul>
					</li>
					<li><a>关于</a></li>
					<li style="margin-left:200px;"><input type="text"><button>搜索</button></li>
				</ul>
			</div>
					
		</div>
		<div class="content">
			<img src="/static/img/goods3.png" />
		</div>
	</body>
</html>

ebuy/per_info/templates/per_info/secure_change_pwd1.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="uft-8">
		<title>输入账号</title>
		<style type="text/css">
			body{
				width:100%;
				height:100%;
			}
			* {
				padding: 0;
				margin: 0;
			}
			.header {
				text-align: center;
				padding-top: 12px;
				padding-bottom: 12px;
				background: #107bf8;
			}
			a ,a:visited, a:link{
				text-decoration: none;
				cursor: pointer;
				color:white;
			}
			.nav {
				width: 1100px;
				margin: 0 auto;
				font-size: 0;
				color:white;
			}
			.nav>ul>li{
				display:inline-block;
				position: relative;
				bottom: 8px;
			}
		</style>
		<style>
		.container {
			width: 100%;
			padding-bottom: 150px;
		}
		.container>div {
			width: 100%;
		}
		.container .section-subnav {
			height: 80px;
			background-color: #f5f5f5;
		}

		.container .section {
			width: 100%;
		}
		.container .section>div {
			width: 1000px;
			margin: 0 auto;
		}
		.container .section_subnav .subnav_process {
			padding-top: 14px;
			text-align: center;
			*margin-left: 60px;
		}
		ul {
			list-style: none;
			padding: 0;
			margin: 0;
		}
		.container .section_subnav .subnav_process>li {
			position: relative;
			display: inline-block;
			*float: left;
		}
		li {
			display: list-item;
			text-align: -webkit-match-parent;
		}
		.container .section_subnav .subnav_process>li>div {
			text-align: center;
			position: relative;
			float: left;
			min-width: 56px;
			height: 34px;
			line-height: 30px;
			vertical-align: middle;
		}
		.container .section_subnav .subnav_process .passed>div>i {
			background-image: url(/static/img/common.png);
			background-position: 0 -404px;
			background-repeat: no-repeat;
			background-color: none;
		}
		.container .section_subnav .subnav_process>li>div>i {
			width: 28px;
			height: 28px;
			font-size: 14px;
			line-height: 28px;
			color: #fff;
		}
	i {
		font-style: normal;
		display: inline-block;
		text-align: center;
		vertical-align: middle;
		background-repeat: no-repeat;
	}
	.container .section_subnav .subnav_process>li>div>p {
		position: relative;
		top: 12px;
		font-size: 14px;
		font-weight: 700;
		line-height: 20px;
		margin-top: -8px;
		color: #a5a5a5;
	}
	p {
		border: none;
		margin: 0;
		padding: 0;
	}
	.container .section_subnav .subnav_process .passed>i {
		background-image: url(/static/img/common.png);
		background-position: 0 -392px;
		background-repeat: no-repeat;
		background-color: none;
	}
	.container .section_subnav .subnav_process>li>i {
		float: left;
		width: 220px;
		height: 2px;
		margin-top: 14px;
		vertical-align: middle;
		background-color: #ededed;
	}
	.container .section_subnav .subnav_process .active>i {
		float: left;
		width: 220px;
		height: 2px;
		margin-top: 14px;
		vertical-align: middle;
		background-color: #ededed;
	}
	.container .section_subnav .subnav_process>li>div>i {
		width: 28px;
		height: 28px;
		font-size: 14px;
		line-height: 28px;
		color: #fff;
		background-image: url(/static/img/common.png);
		background-position: 0 -442px;
		background-repeat: no-repeat;
		background-color: none;
	}
	.container .section_subnav .subnav_process>li>i {
		float: left;
		width: 220px;
		height: 2px;
		margin-top: 14px;
		vertical-align: middle;
		background-color: #ededed;
	}
	.container .section_subnav .subnav_process .last {
		margin-right: 0;
	}
	.container .section_subnav .subnav_process .last>i {
		display: none;
	}
	</style>
	<style>
		#input_find_phone{
			margin-top: 8px;
			padding: 3px;
			border-radius: 2px;
			padding-left: 5px;
			height: 28px;
			font-size: 15px;
			border: 0.7px solid;
		}
		#input_account_form{
			width: 300px;
			left: 40%;
			position: absolute;
			top: 50px;
		}
		.main_form{
			position:relative;
		}
		.xxxx input{
			position:relative;
		}
		.button-style{
			position:absolute;
			top:35px;
			margin-top:80px;
		}
		#tipword_input_find_qq{
			color:red;

		}
		.tips-error-text{
			margin-top:9px;
		}
		#submit_info{
			background-color:#107bf8;
			width:70px;
			height:40px;
			border-color:#107bf8;
			color:white;
		}
		#submit_info:hover{
			cursor:pointer;
		}

	</style>
	</head>

	<body>
		<div class="header">
			<div class="nav">
				<ul class="ul_one">
					<li style="margin-right:5px;position: initial;"><img src="/static/img/secure_logo.png" style="width: 130px;height: 35px;"></li>
					<li style="margin-right:400px;position: initial;"><img src="/static/img/secure_logo2.png" style="width: 120px;height: 30px;"></li>
					<li style="margin-left:100;position: initial;"><img src="/static/img/secure_logo3.png" style="width: 210px;height: 28px;"></li>
				</ul>
			</div>

		</div>
		<div class="container">
    		<div>
                <div class="section section-subnav">
                    <div class="section_subnav">
                        <ul class="subnav_process">
                            <li class="passed">
                                <div>
                                    <i>1</i>
                                    <p>填写账号</p>
                                </div>
                                <i></i>
                            </li>
                            <li class="active">
                                <div>
                                    <i>2</i>
                                    <p>身份验证</p>
                                </div>
                                <i></i>
                            </li>
                            <li>
                                <div>
                                    <i>3</i>
                                    <p>设置新密码</p>
                                </div>
                                <i></i>
                            </li>
                            <li class="last">
                                <div>
                                    <i>4</i>
                                    <p>完成</p>
                                </div>
                                <i></i>
                            </li>
                        </ul>
                    </div>
                </div>
				<div class="section section-main">
					<div class="section_main" id="container">
						<div class="main_form">
							<form enctype="multipart/form-data" action="{% url 'per_info:handle_page_one' %}" id="input_account_form" method="post">
								<div class="mod-form-block input">
									<label>帐号：</label>
									<div class="xxxx">
										<div class="formblock medium" style="width:264px">
											<input type="text" style="width:264px" id="input_find_phone" name="phone" placeholder="手机号">
										</div>
										<div class="tips-error-text" style="display:block" id="tipdiv_input_find_qq">
											<div>
												{% if flag %}
													{% if flag == 2 %}
													<span id="tipword_input_find_qq">帐号有误，请重新输入</span>
													{% elif flag == 0 %}
													<span id="tipword_input_find_qq"></span>
													{% else %}
													<span id="tipword_input_find_qq">意外错误</span>
													{% endif %}
												{% endif %}
											</div>
										</div>
										<div class="button-style">
											<div class="confirm" style="width:264px">
												<input id="submit_info" type="submit">
											</div>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
		        </div>
			</div>
    	</div>
	</body>
</html>

ebuy/per_info/templates/per_info/show_info.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>个人信息</title>
<style type="text/css">
	*{
		padding: 0px;
		margin: 0px;
	}

.page_content {
    height: 750px;
    width: 700px;
	margin:0 auto;
}
.page_content #myebuyinfo {
    width: 100%;
    height: 100%;
    top: 20px;
    position: relative;
}
.info_header ul li {
    height: 40px;
    font-size: 30px;
    text-align: center;
}
.info_header ul{
	list-style: none;
}
.info_header {
	border: 1px solid #000000;
}
#myebuyinfo .info_content>div {
	min-height: 400px;
    border-bottom: 1px solid #000000;
	border-left: 1px solid #000000;
	border-right: 1px solid #000000;
    padding: 10px;
    background-color: #fff;
    zoom: 1;
}
	td{
		padding-top:40px;
		text-align: center;
	}
	.align_right{
		text-align: right;
	}
	#profile{
		border: 3px solid;
		padding: 5px;
		border-color: #b5aca1ba;
	}
	#upfilebutton {
		font-size: 18px;
		background-color: tomato;
		color: white;
		border-radius: 5px;
		cursor:pointer;
	}
	    #reg_btn{
			border-radius: 10px;
			border-width: 2px;
			width: 50%;
			height: 50px;
			background: #ff4401;
			border-color: #dfdfdf;
			text-align: center;
			line-height: 50px;
			color: #ffffff;
            font-size: 18px;
			font-weight:bold;
        }
        #reg_btn:hover{
            cursor:pointer;
        }
	#user_nickname{
		font-size:15px;
		height:25px;
	}
</style>
</head>

<body>
		<div class="header">
			<div class="nav clearfix">
				<ul class="ul_one">
					<li style="margin-right:20px;position: initial;"><img src="/static/img/logo_new.jpg" style="width: 130px;height: 35px;"></li>
					<li><a href="{% url 'per_info:info_main' %}" style="margin-right:20px;">首页</a></li>
					<li>
						<a style="margin-right:15px;">账户设置 ˇ</a>
						<ul class="two" style="z-index: 99999;width:85px; position: absolute;left: -38px;top: 15px;">
							<li style="margin-top:9px; border-top:solid;border-top-color:#90dae633;"><a href="{% url 'per_info:show_info' %}">个人资料</a></li>
							<li style="border-bottom:solid;border-bottom-color:#90dae633;"><a href="{% url 'per_info:modify_pwd' %}" target="_blank">修改密码</a></li>
						</ul>
					</li>
					<li><a>关于</a></li>
					<li style="margin-left:200px;"><input type="text"><button>搜索</button></li>
				</ul>
			</div>

</div>
<div class="page_content">
	<div id="myebuyinfo" class="grid1">
		<div class="info_header">
			<ul>
				<li>基本信息</li>
			</ul>
		</div>
		<div class="info_content">
			<div>
					<table width="500px">
						<tr>
						  <td>当前头像:</td>
						  <td class="align_right">
                              {% if user.user_pic == '' %}
							  <img id="profile" width="100px" height="100px" src="/static/img/default_profile.jpg" />
                              {% else %}
                              <img id="profile" width="100px" height="100px" src="/static/profile/{{user.user_pic}}" />
                              {% endif %}
							</td>
							<td>
								<button id="upfilebutton" onclick="F_Open_dialog()">上传头像</button>
							</td>
						</tr>
					</table>
				<form enctype="multipart/form-data" action="{% url 'per_info:modify_info' %}" method="post">
					<table width="420px">
						<tr>
						  <td>&nbsp;&nbsp;&nbsp;昵称:</td>
						  <td class="align_right"><input id="user_nickname" type="text" name="user_nickname" value="{{user.user_nickname}}"></td>
						  <td></td>
						</tr>
						<tr>
							<td>
								<input type="file" id="upfile" name="upload" style="display: none;" accept="image/png, image/jpeg, image/gif, image/jpg" onchange="">
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<div class="btn_red">
									<input type="submit" value="保存" id="reg_btn">
								</div>
							</td>
						</tr>
					</table>
				</form>
			</div>
		</div>
	</div>
</div>
</body>
		<style type="text/css">
			body{
				width:100%;
				height:100%;
			}
			* {
				padding: 0;
				margin: 0;
			}
			.header {
				text-align: center;
				padding-top: 12px;
				padding-bottom: 12px;
				background: #ff4401;
			}
			a ,a:visited, a:link{
				text-decoration: none;
				cursor: pointer;
				color:white;
			}
			.nav {
				width: 1000px;
				margin: 0 auto;
				font-size: 0;
				color:white;
			}
			.nav>ul>li{
				display:inline-block;
				position: relative;
				bottom: 8px;
			}
			.nav>ul>li>a {
				font-size: 18px;
				display: inline-block;
				width: 100px;
			}
			.nav>ul>li>a:hover {
				background-color: #942b06;
			}
			.local {
				margin-left: 30px;
			}
			.adm {
				margin-left: 25px;
			}
			.content img{
				width:1519px;
				height:1849px;
			}
			.clearfix{
                *zoom:1;
            }
            .clearfix:after{
                clear: both;
            }
			.two,.two>li{list-style: none;}
			.two{display:none;font-size: 12px;}
			.ul_one>li:hover .two{display: block;}{

			}
			.two li{height:20px;width:200%;padding: 10px 0;transition: .4s;color:black;background-color:white;    border-left: solid;
				border-right: solid;
				border-color: #90dae633;
			}
			.two li:hover{}
			.two li a:hover{
				color:#ff4401;

			}
			.two a{
				color:black;
			}
		</style>
	<script>
		function F_Open_dialog() {
			document.getElementById("upfile").click();
		}
		document.getElementById('upfile').onchange = function() {
			var maxsize = 2 * 1024 * 1024; //设置文件大小2兆
			var maxMsg = "上传的图片不能超过2兆";
			var tipMsg = "您的浏览器不支持计算上传文件大小，请上传2兆以内的文件，建议使用谷歌浏览器";
			var browserCfg = {};
			var ua = window.navigator.userAgent;
			if (ua.indexOf("Firefox") >= 1) {
				browserCfg.firefox = true;
			} else if (ua.indexOf("Chrome") >= 1) {
				browserCfg.chrome = true;
			}
			try{
				var obj_file = document.getElementById("upfile");
				if (obj_file.value == "") {
					alert("请先选择上传文件");
					return;
				}
				var filesize = 0;
				if (browserCfg.firefox || browserCfg.chrome) {
					filesize = obj_file.files[0].size;
				} else {
					alert(tipMsg);
					return;
				}
				if(filesize==-1){
					alert(tipMsg);
					return;
				}else if(filesize>maxsize){
					alert(maxMsg);
					return;
				}else{
					var imgFile = this.files[0];
					var fr = new FileReader();
					fr.onload = function() {
						document.getElementById('profile').src = fr.result;
					};
					fr.readAsDataURL(imgFile);
				}
			}catch(e){
				alert(e);
			}
		};
	</script>
</html>