ebuy/ebuy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reg_login.urls', namespace='reg_login')),
    path('test/', include('per_info.urls', namespace='per_info')),
]

ebuy/per_info/urls.py
from django.urls import path, re_path
from . import views

app_name = 'per_info'
urlpatterns = [
    path('info_main/', views.info_main, name='info_main'),
    path('info_main/show_info', views.show_info, name='show_info'),
    path('info_main/modify_info', views.modify_info, name='modify_info'),
    path('info_main/modify_pwd', views.modify_pwd, name='modify_pwd'),
    path('info_main/handle_page_one', views.handle_page_one, name='handle_page_one'),
    re_path('info_main/handle_page_two/(?P<phone_number>[0-9]+)$', views.handle_page_two, name='handle_page_two'),
    re_path('info_main/handle_page_three/(?P<phone_number>[0-9]+)$', views.handle_page_three, name='handle_page_three'),
    path('index/', views.test)
]

ebuy/reg_login/urls.py
from django.urls import path, re_path
from . import views

app_name = 'reg_login'
urlpatterns = [
    path('', views.dispatcher),
    path('index/', views.index, name='index'),
    path('reg_login/login', views.login, name='login'),
    path('reg_login/reg', views.reg, name='reg'),
    path('reg_login/handle_reg', views.handle_reg, name='handle_reg'),
    path('reg_login/handle_login', views.handle_login, name='handle_login'),
    path('reg_login/logout', views.logout, name='logout')
]

ebuy/reg_login/models.py
from django.db import models
# Create your models here.


class User(models.Model):
    user_phone = models.CharField(primary_key=True, max_length=11)
    user_password = models.CharField(max_length=35)
    user_nickname = models.CharField(max_length=30)
    user_pic = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'user'


class Secure(models.Model):
    user_verify_question = models.CharField(max_length=40)
    user_verify_answer = models.CharField(max_length=40)
    user_to = models.ForeignKey(to=User, related_name='user_verify', on_delete=models.CASCADE)

    class Meta:
        db_table = 'user_verify'

ebuy/reg_login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models
from django.template import loader ,Context
from django.http import HttpResponse
import os, time
# Create your views here.


def dispatcher(requset):
    return redirect('index/')


def index(request):
    is_login = request.session.get("is_login", None)
    if is_login:
            user_phone = request.session.get('user_phone')
            user_list = models.User.objects.filter(pk=user_phone)
            if user_list:
                response = render(request, 'templates/reg_login/index.html', {'login': 1, 'user': user_list[0], 'default_profile': 'default_profile'})
                # response.set_cookie('user_phone', user_list[0].user_phone, 259220)
                return response
    return render(request, 'templates/reg_login/index.html')


def login(request):
    return render(request, 'templates/reg_login/login.html')


def reg(request):
    return render(request, 'templates/reg_login/reg.html')


# 处理注册提交的表单
def handle_reg(request):
    if request.method == "GET":
        return redirect('reg_login:reg')
    flag = 0  # 是否错误的标志
    user = models.User()
    user.user_phone = ''
    user.user_password = ''
    user.user_nickname = ''
    user.user_pic = ''
    user_verify_one = models.Secure()
    user_verify_two = models.Secure()

    if request.method == 'POST':
        user.user_phone = request.POST.get('phone')
        user.user_password = request.POST.get('password')
        user.user_nickname = request.POST.get('nickname')
        user_verify_one.user_verify_question = '父亲姓名'
        user_verify_one.user_verify_answer = request.POST.get('father_name')
        user_verify_two.user_verify_question = '母亲姓名'
        user_verify_two.user_verify_answer = request.POST.get('mother_name')
        if user.user_phone == '' or user.user_password == '' or user.user_nickname == '' or user_verify_one.user_verify_answer == '' or user_verify_two.user_verify_answer == '':
            flag = 1
        if len(user.user_password) < 8 or len(user.user_password) > 15 :
            flag = 1
        if len(user.user_phone) != 11:
            flag = 1
        if flag != 0:
            return render(request, 'templates/reg_login/reg.html', {'flag': flag})
        userindb = models.User.objects.filter(pk=user.user_phone)
        if not userindb:
            try:
                image = request.FILES.get('upload', None)
                if image:
                    user.user_pic = str(int(time.time()*10000)) + '.jpg'
                    dist = open(os.path.join('./reg_login/static/profile/', user.user_pic), 'wb')
                    for chunk in image.chunks():
                        dist.write(chunk)
                    dist.close()
            except:
                flag = 1
        else:
            flag = 2
    if user.user_phone == '' or user.user_password == '' or user.user_nickname == '':
        flag = 1
    if len(user.user_password) < 8 or len(user.user_password) > 15:
        flag = 1
    if len(user.user_phone) != 11:
        flag = 1

    if flag != 0:
        return render(request, 'templates/reg_login/reg.html', {'flag': flag})
    else:
        user.save()
        userindb2 = models.User.objects.filter(pk=user.user_phone)
        user_verify_one.user_to = userindb2[0]
        user_verify_two.user_to = userindb2[0]
        user_verify_one.save()
        user_verify_two.save()
        return render(request, 'templates/reg_login/reg_success.html')


# 处理登录提交的表单
def handle_login(request):
        if request.method == "GET":
            return redirect('reg_login:login')
        flag = 0
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        remember = request.POST.get('remember')
        user = models.User.objects.filter(pk=phone)
        if user:
            if password == user[0].user_password:
                pass
            else:
                flag = 2
        else:
            flag = 1
        if flag != 0:
            return render(request, 'templates/reg_login/login.html', {'flag': flag})
        else:
            response = render(request, 'templates/reg_login/index.html', {'login': 1, 'user': user[0], 'default_profile': 'default_profile'})
            if remember is None:
                request.session['user_phone'] = user[0].user_phone
                request.session['is_login'] = True
                request.session['remember'] = False
                request.session.set_expiry(0)
            else:
                request.session['user_phone'] = user[0].user_phone
                request.session['is_login'] = True
                request.session['remember'] = True
                # response.set_cookie('user_phone', phone, 259220)
            return response


# 处理注销操作
def logout(request):
    response = render(request, 'templates/reg_login/index.html')
    # response.delete_cookie('user_phone')
    request.session.clear()
    return response

ebuy/reg_login/templates/reg_login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>首页</title>
  <link rel="stylesheet" href="/static/css/forLSK.css">
  <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
<div class="mmall-head">
  <p class="f-left user-log-info
  {% if login %}
	login
  {% else %}
	logout
  {% endif %}
  ">
    <span class="welcome mmall-text">喵，欢迎来易购</span>
    <a class="login-link mmall-text with-cursor" href="{% url 'reg_login:login' %}" target=>请登录</a>
    <a class="register-link mmall-text with-cursor" href="{% url 'reg_login:reg' %}" target=>免费注册</a>
    <a class="user-name mmall-text" href="{% url 'per_info:info_main' %}">{{user.user_phone}}</a>
    <a class="logout-link mmall-text with-cursor" href="{% url 'reg_login:logout' %}">退出</a>
  </p>
  <p class="f-right">
    <a class="welcome mmall-text with-cursor" href="{% url 'per_info:info_main' %}" target="_blank">我的易购</a>
    <a class="welcome mmall-text with-cursor" href="#" target="_blank">购物车</a>
    <span class="welcome mmall-text with-cursor" href="#" target="_blank">收藏夹</span>
  </p>
</div>
<div class="mmall-body width-1180">
  <!-- 搜索框 -->
  <div class="mmall-search-wrap">
    <input type="text" class="mmall-search" placeholder="搜索 易购 商品/品牌/店铺">
    <button class="mmall-search-btn with-cursor">搜索</button>
  </div>

  <!-- 品类 -->
  <div class="mmall-category-wrap">
    <div class="mmall-category-head">
      <ul class="mmall-category-head-list">
        <li class="mmall-category-head-list-item">
          <a href="./category.html">商品分类</a>
        </li>
        <li class="mmall-category-head-list-item">
          <a href="./mmall.html">易购商城</a>
        </li>
        <li class="mmall-category-head-list-item">
          <a href="./intern.html">易购国际</a>
        </li>
      </ul>
    </div>
    <div class="mmall-category-body">
      <div class="mmall-category-side-list">
        <div class="side-list-item with-cursor" data-text="women">女装</div>
        <div class="side-list-item with-cursor" data-text="men">男装</div>
        <div class="side-list-item with-cursor" data-text="shoes">女鞋/男鞋</div>
        <div class="side-list-item with-cursor" data-text="makeup">美妆/个人护理</div>
        <div class="side-list-item with-cursor" data-text="digital">数码3C</div>
        <div class="side-list-item with-cursor" data-text="foodDrink">美食饮品</div>
        <div class="side-list-item with-cursor" data-text="furniture">家具</div>
        <div class="side-list-item with-cursor" data-text="books">图书</div>
        <div class="side-list-item with-cursor" data-text="sports">运动户外</div>
        <div class="side-list-item with-cursor" data-text="medicine">医药</div>
        <div class="side-list-item with-cursor" data-text="infant">母婴</div>
        <div class="side-list-item with-cursor" data-text="fruits">生鲜水果</div>
        <div class="side-list-item with-cursor" data-text="snacks">零食</div>
        <div class="side-list-item with-cursor" data-text="electricAppliance">家电</div>
      </div>
      <ul class="mmall-category-side-list-content women" id="categoryContent">
        <li class="shoes-item">靴子</li>
        <li class="women-item">女装</li>
        <li class="men-item">男装</li>

        <li class="makeup-item">美妆/个人护理</li>
        <li class="digital-item">数码3C</li>
        <li class="foodDrink-item">美食饮品</li>
        <li class="furniture-item">家具</li>
        <li class="books-item">图书</li>
        <li class="sports-item">户外运动</li>
        <li class="medicine-item">医药</li>
        <li class="infant-item">母婴</li>
        <li class="fruits-item">生鲜水果</li>
        <li class="snacks-item">零食</li>
        <li class="electricAppliance-item">家电</li>
      </ul>
    </div>
  </div>
</div>
<div class="mmall-footer"></div>

<script>
  $(document).ready(function () {
    $('.side-list-item').on('mouseenter', function() {
      const allListItem = $('.side-list-item');
      const dataTextCls = $(this).data('text');

      for(let i = 0, len = allListItem.length; i < len; i++) {
        const curItem = $(allListItem[i]).data('text');
        $('#categoryContent').removeClass(curItem);
      }

      $('#categoryContent').addClass(dataTextCls);
    })
  });
</script>
</body>
</html>

ebuy/reg_login/templates/reg_login/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>登录页面</title>
<link rel="stylesheet" href="/static/css/login.css">
</head>
<body>
	<div id="page_header">
		<div class="logo">
			<div id="ebuy_pic"><img src="/static/img/logo.jpg"></div>
			<div id="ebuy_notice"><p>为确保您账户的安全及正常使用，依《网络安全法》相关要求，6月1日起会员账户需绑定手机。如您还未绑定，请尽快完成，感谢您的理解及支持！</p></div>
		</div>
	</div>
<div class="content">
    <div class="login-newbg"></div>
    <div class="login">
        <div class="header">
            <h1>
                <a id="a1" href="{% url 'reg_login:login' %}">登录</a> <a id="a2" href="{% url 'reg_login:reg' %}">注册</a>
            </h1>

        </div>
        <form action="{% url 'reg_login:handle_login' %}" method="post">
            <table>
                <tr>
                    <td class="td1">用户名(手机)</td>
                    <td><input type="text" class="input1" name="phone" required="true"></td>
                    <td>
                        {% if flag %}
                            {% if flag == 1 %}
                            <span class="tishi3">账户不存在</span>
                            {% else %}
                            <span class="tishi3"></span>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="td1">密码</td>
                    <td><input type="password" class="input1" name="password" required="true"></td>
                    <td>
                        {% if flag %}
                            {% if flag == 2 %}
                            <span class="tishi3">密码错误</span>
                            {% else %}
                            <span class="tishi3"></span>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="td1" colspan="2">
                        <input type="checkbox" name="remember" value="true" checked="checked"> 记住用户名</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="btn-red">
                            <input type="submit" value="登录" id="login-btn">
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</body>
</html>

ebuy/reg_login/templates/reg_login/reg.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>注册</title>
<link rel="stylesheet" href="/static/css/reg.css">
<script>
function validatephonenum(str){
        var re = /^1\d{10}$/
        if (re.test(str)) {
			document.getElementById("tishi").innerHTML="";
			document.getElementById("reg-btn").disabled = false;
        } else {
			document.getElementById("tishi").innerHTML="格式错误";
			document.getElementById("reg-btn").disabled = true;
        }
}

function validatepwd() {
              var pwd1 = document.getElementById("pwd1").value;
              var pwd2 = document.getElementById("pwd2").value;
		<!-- 对比两次输入的密码 -->
              if(pwd1 == pwd2) {
                  document.getElementById("tishi2").innerHTML="<font color='green'></font>";
                  document.getElementById("reg-btn").disabled = false;
              }
              else {
                document.getElementById("tishi2").innerHTML="密码不一致";
                document.getElementById("reg-btn").disabled = true;
              }
          }
</script>
</head>
<body>
	<div id="page_header">
		<div class="logo">
			<div id="ebuy_pic"><img src="/static/img/logo.jpg"></div>
			<div id="ebuy_notice"><p>为确保您账户的安全及正常使用，依《网络安全法》相关要求，6月1日起会员账户需绑定手机。如您还未绑定，请尽快完成，感谢您的理解及支持！</p></div>
		</div>
	</div>
<div class="content">
    <div class="login-newbg"></div>
    <div class="reg">
        <div class="header">
            <h1>
                <a href="{% url 'reg_login:login' %}">登录</a> <a href="{% url 'reg_login:reg' %}">注册</a>
            </h1>
        </div>
		<div class="uploadfile">
			<div id="usertouxiang">
				<img id="userimage" src="/static/img/default_profile.jpg" /><!-- 给予一个初始默认图片，不然显示不太友好 -->
			</div>
			<div class="uplabel">
				<center><button id="upfilebutton" onclick="F_Open_dialog()">上传头像</button></center>
			</div>
		</div>
        <form enctype="multipart/form-data" action="{% url 'reg_login:handle_reg' %}" method="post">
            <table>
			<tbody>
                <tr>
                    <td class="td1">手机号</td>
                    <td><input type="text" class="input1" id="phonenum" name="phone" required="true" onchange="validatephonenum(phonenum.value)"></td>
                    <td class="warning"><span id="tishi"></span></td>
                </tr>
                <tr>
                    <td class="td1">密码</td>
                    <td><input type="password" class="input1" id="pwd1" name="password" minlength="8" maxlength="15" required="true"></td>
                    <td></td>
                </tr>
				<tr>
                    <td class="td1">确认密码</td>
					<td><input type="password" class="input1" id="pwd2" name="password_confirm" maxlength="15" required="true" onkeyup="validatepwd()"></td>
                    <td class="warning"><span id="tishi2"></span></td>
                </tr>
                <tr>
                    <td class="td1">昵称</td>
                    <td><input type="text" class="input1" name="nickname" required="true"></td>
                    <td></td>
                </tr>
				<tr>
                    <td class="td1" colspan="3" style="text-align:center;">密保问题</td>
                </tr>
				<tr>
                    <td class="td1">父亲姓名</td>
                    <td><input type="text" class="input1" name="father_name" required="true"></td>
                    <td></td>
                </tr>
				<tr>
                    <td class="td1">母亲姓名</td>
                    <td><input type="text" class="input1" name="mother_name" required="true"></td>
                    <td></td>
                </tr>
				<tr>
					<td>
						<input type="file" id="upfile" name="upload" style="display: none" accept="image/png, image/jpeg, image/gif, image/jpg"
						 onchange="" />
					</td>
				</tr>
                <tr>
                    <td id="error1" height="30.4px" colspan="3">
                        {% if flag %}
                            {% if flag == 1 %}
                                遇到意外错误，请重试!
                            {% elif flag == 2 %}
                                手机号已注册!
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
				</tbody>
            </table>
                <div class="btn-red">
                    <input type="submit" value="注册" id="reg-btn">
                </div>
        </form>
    </div>
</div>
</body>
	<script>
		function F_Open_dialog() { 
			document.getElementById("upfile").click(); 
		}
		document.getElementById('upfile').onchange = function() {
			var maxsize = 2 * 1024 * 1024; //设置文件大小2兆
			var maxMsg = "上传的图片不能超过2兆";
			var tipMsg = "您的浏览器不支持计算上传文件大小，请上传2兆以内的文件，建议使用谷歌浏览器";
			var browserCfg = {};
			var ua = window.navigator.userAgent;
			if (ua.indexOf("Firefox") >= 1) {
				browserCfg.firefox = true;
			} else if (ua.indexOf("Chrome") >= 1) {
				browserCfg.chrome = true;
			}
			try{
				var obj_file = document.getElementById("upfile");
				if (obj_file.value == "") {
					alert("请先选择上传文件");
					return;
				}
				var filesize = 0;
				if (browserCfg.firefox || browserCfg.chrome) {
					filesize = obj_file.files[0].size;
				} else {
					alert(tipMsg);
					return;
				}
				if(filesize==-1){
					alert(tipMsg);
					return;
				}else if(filesize>maxsize){
					alert(maxMsg);
					return;
				}else{
					var imgFile = this.files[0];
					var fr = new FileReader();
					fr.onload = function() {
						document.getElementById('userimage').src = fr.result;
					};
					fr.readAsDataURL(imgFile);
				}
			}catch(e){
				alert(e);
			}
		};
	</script>
</html>

ebuy/reg_login/templates/reg_login/reg_success.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>注册成功</title>
<link rel="stylesheet" href="/static/css/reg_success.css">
</head>
<body>
    <div class="login">
		<span>恭喜您,注册成功!</span>
		<a href="{% url 'reg_login:login' %}">点击登录</a>
    </div>
</body>
</html>

ebuy/reg_login/templates/reg_login/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{flag}}
</body>
</html>